spring:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: false
  datasource:
    url: "jdbc:postgresql://localhost:5432/forismatic-proxy"
    username: veinhorn
    password: root
  liquibase:
    change-log: classpath:liquibase-changelog.xml
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
