spring:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/forismatic-proxy"
    username: veinhorn
    password: root
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher